services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    network_mode: host
    build:
      dockerfile: docker/DockerFile
    container_name: app
    depends_on:
      - db
    volumes:
      - ./target:/target
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/testdb
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    network_mode: host
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres